=== PascalCase/PlayCustomParameters/ttworkbench.play.parameters.ipv6/src/ttworkbench/play/parameters/ipv6/widgets/tableviewer/widget.parameters.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://github.com/TestingTechnologies/PlayCustomParameters" xmlns:tns="https://github.com/TestingTechnologies/PlayCustomParameters">

  <xs:complexType name="Attribute">
	<xs:simpleContent>
		<xs:extension base="xs:string">
		  <xs:attribute type="xs:string" name="name"/>
		</xs:extension>
	</xs:simpleContent>
  </xs:complexType>

  <xs:element name="settings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="widgets">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="widget" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="description" minOccurs="0"/>
                    <xs:element name="image" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="path"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="editor" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="parameterId" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="name" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="parameters">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="parameter" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="defaultValue" minOccurs="0"/>
                    <xs:element name="description" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="visible"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="validator" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element name="relation" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:short" name="parameterId" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element name="attribute" type="tns:Attribute" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="id" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="validators">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="validator" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="classpath"/>
                    <xs:element name="attribute" type="tns:Attribute" minOccurs="0" maxOccurs="unbounded" />
                  </xs:sequence>
                  <xs:attribute type="xs:string" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== PascalCase/PlayCustomParameters/ttworkbench.play.parameters.settings/src/main/resources/widget.parameters.xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="https://github.com/TestingTechnologies/PlayCustomParameters" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://github.com/TestingTechnologies/PlayCustomParameters widget.parameters.xsd ">

	<widgets>
		<widget name="Custom Widget 1">
			<description>text</description>
			<image path="path" />
			<editor parameterId="PX_123" />
			<editor parameterId="456" />
		</widget>
		
		<widget name="Custom Widget 2">
			<editor parameterId="789" />
			<editor parameterId="000" />
			<editor parameterId="123" />
			<editor parameterId="PX_NAME1" />
		</widget>
	</widgets>
	
	
	<parameters>
		
		<parameter id="123">
			<defaultValue>9283248230958dasd</defaultValue>
			<description visible="false">Beschreibung</description>
		</parameter>
		
		<parameter id="456">
			<validator id="v456" />
		</parameter>
		
		<parameter id="789">
			<validator id="v789" />
			<validator id="vXXX">
				<relation parameterId="123" />
			</validator>
		</parameter>
		
		<parameter id="000">
			<validator id="v000" />
			<validator id="vXXX">
				<relation parameterId="123" />
				<relation parameterId="456" />
			</validator>
			<validator id="vYYY">
				<relation parameterId="789" />
				
				<attribute name="attr1">value1</attribute>
			</validator>
		</parameter>
		
	</parameters>
	
	<validators>
		<validator id="v456">
			<classpath>edu.nothing.here.Validator456</classpath>
			<attribute name="attr1">value1</attribute>
		</validator>
		<validator id="v789">
			<classpath>edu.nothing.here.Validator789</classpath>
		</validator>
		<validator id="vXXX">
			<classpath>edu.nothing.here.ValidatorXXX</classpath>
		</validator>
		<validator id="vYYY">
			<classpath>edu.nothing.here.ValidatorYYY</classpath>
		</validator>
	</validators>
</settings>
